apiVersion: v1
kind: ServiceAccount
metadata:
  name: scone-runner
  namespace: scone-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scone-runner
  namespace: scone-tools
rules:
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get","list","watch","create","delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scone-runner
  namespace: scone-tools
subjects:
- kind: ServiceAccount
  name: scone-runner
  namespace: scone-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scone-runner

